### ISSUE TITLE
warnings rather than errors

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#117]
@catalamarti @ablack3 Relevant to #114, but also more generally, we need to think about how strict we want to be with validating the cdm, ie when we want to throw warnings and when errors

**Comment by edward-burn** [comment]
@catalamarti how about:
- warning if omop table is missing expected columns, table still included in cdm reference
- warning if records in cohort tables don't satisfy all requirements (in observation, etc)

Later release
- change to warning if omop table is missing expected columns, but table no longer included in cdm reference (?)
- change to error if records in cohort tables don't satisfy all requirements (in observation, etc)

This will allow downstream packages more time to satisfy the rules in their testing and give users notice of upcoming changes

**Comment by catalamarti** [comment]
#124 part of this is done here
