### ISSUE TITLE
summarisedResult() crushes for empty dataframes

### ISSUE THREAD

**Issue by nmercadeb** [darwin-eu-dev/omopgenerics#129]
dplyr::tibble(cdm_name = "a", result_type = "a", package_name = "a", package_version = "a", group_name = "a", group_level = "a", strata_name = "a", strata_level = "a", variable_name = "a", variable_level = "a", estimate_name = "a", estimate_type = "a", estimate_value = "a", additional_name = "a", additional_level = "a") |> dplyr::filter(cdm_name != "a") |> omopgenerics::summarisedResult()

**Comment by catalamarti** [comment]
this has been solved now #130 and in fact we have a new function called: emptySummarisedResult() that provides you an empty summarised_result object
@nmercadeb
