### ISSUE TITLE
default path in export

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/OMOPGenerics#13]
At the moment export has a default of `path = here::here()`, @catalamarti I'm thinking it might be better to not have a default here (as in a typical network study this is not going to be the path to results). Or if we do want to keep the default, using here::here("Results") might better fit with how we currently do network studies.

**Comment by catalamarti** [comment]
Agreed no default @edward-burn

**Comment by catalamarti** [comment]
- delete default path ans ask to be provided

**Comment by MimiYuchenGuo** [comment]
@catalamarti  to do it
