### ISSUE TITLE
suppress method

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/OMOPGenerics#15]

**Comment by catalamarti** [comment]
suppress.SummarisedResult

**Comment by catalamarti** [comment]
- To export a suppress method
- To create suppress.summarised_result: see for ideas https://github.com/darwin-eu-dev/PatientProfiles/blob/supress_counts_new/R/suppressCount.R

**Comment by MimiYuchenGuo** [comment]
I am happy to do it and will be very fast
