### ISSUE TITLE
emptyCohortTable

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#150]
like #147, providing an empty cohort table could I think be a nice utility function

**Comment by catalamarti** [comment]
the problem of this is what to provide in the cohort set and attrition? also empty? then whats the point of having this function?

**Comment by edward-burn** [comment]
I guess my idea is that halfway through incidence prevalence I might realise that there is nobody going to be in the denominator so I want to return an empty cohort table in the database, but yes I see why this might not be so necessary as it doesn’t save me much work in the end

**Comment by catalamarti** [comment]
create 3 empty table with the correct types

**Comment by catalamarti** [comment]
#172
