### ISSUE TITLE
create a reexport guide

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/omopgenerics#156]
- If a package generates a cdm object should reexport: cdmReference, cdmSource, insertTable, dropTable
- if a package generates a cohort object should reexport: settings, attrition, cohortCount

Can we get some sort of rules for the packages? What do you think @ablack3 @edward-burn

**Comment by ablack3** [comment]
I don't think we want several packages creating cdm objects. this is/was the main purpose of cdmconnector in my mind actually: the creation of the cdm object. 

Analytic packages might create various cohort-like objects or results objects though. 
So I'd say we should keep  the reexporting of cdmReference, cdmSource, insertTable, dropTable to just CDMConnector if that is ok.

But other packages should reexport settings, attrition, cohortCount if they produce cohort-like objects. 
And we also need reexports for summarized results and methods relating to them.

**Comment by catalamarti** [comment]
yep for the moment it is only cdmconnector, but just in case in the future we built sth else. But yes, this would only apply to cdmconnector.

**Comment by ablack3** [comment]
We should be careful not to create interdependency hell.
