### ISSUE TITLE
filter setting and attrition in newCohortTable to macth id's in table

### ISSUE THREAD

**Issue by nmercadeb** [darwin-eu-dev/omopgenerics#158]
Do you think it could be worth to implement this, so the code below could generate a table with the correct settings and attrition? @catalamarti @edward-burn 

cdm[[targetCohortName]] %>%
      dplyr::filter(.data$cohort_definition_id == .env$targetCohortId) %>%
      dplyr::compute(name = name, temporary = FALSE) %>%
      omopgenerics::newCohortTable()

**Comment by edward-burn** [comment]
I guess this would be handled if we do https://github.com/darwin-eu-dev/omopgenerics/issues/155 @catalamarti ?

**Comment by catalamarti** [comment]
I dont think this is more complicated that we think, imagine that I do:
`cdm[[targetCohortName]] %>% inner_join(cdm$xxx)`
We would like to keep the cohort set even if we have lost one of the cohorts...

Any suggestion @edward-burn @nmercadeb

**Comment by catalamarti** [comment]
would you be happy with:
subsetCohort(cohort, cohortId, name = tableName(cohort))
?

@nmercadeb @edward-burn
