### ISSUE TITLE
insertTable vs insertFromSource

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#163]
Say I create a table in the database but it is not yet in the cdm. I was adding it to my cdm using insertTable, but I hadn't realised this had a collect so it was reading the data out of the database and then putting it back in. Instead I should be using insertFromSource, right @catalamarti? It would be good to make this more obvious if so (maybe a more intuitive name?!), and perphaps this should also be reexported?

**Comment by edward-burn** [comment]
Maybe a warning could be added if a user is trying to use this function with the same source?

**Comment by edward-burn** [comment]
Perhaps insertTable could also use insertFromSource internally?

**Comment by catalamarti** [comment]
throw error if it is not a data.frame
