### ISSUE TITLE
merge empty and creation function?

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/omopgenerics#175]
So I've seen in other packages that if you call the creator of a class and do not provide any argument then an empty one is created.

```
tibble() # would create an empty tibble
```

So maybe we can merge `newCohortTable()` and `emptyCohortTable()`, `newCdmReference` and `emptyCdmReference`, and so...?

What do you think @edward-burn @ilovemane

**Comment by edward-burn** [comment]
very true @catalamarti, I think that would make sense and the keep the empty* ones as internal functions for this

**Comment by catalamarti** [comment]
decided to keep them separate for the moment
