### ISSUE TITLE
newCdmSource should not leave any tables behind in the cdm object.

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/omopgenerics#176]
newCdmSource leaves tables in the cdm object. Maybe I did something that caused this when I changed dropTables in cdmConnector. I'm not sure. 

``` r
con <- DBI::dbConnect(duckdb::duckdb(dbdir = CDMConnector::eunomia_dir()))

writeSchema <- c(schema = "main", prefix = "prefix")

source <- structure(
  .Data = list(),
  "dbcon" = con,
  "write_schema" = writeSchema
)
class(source) <- "db_cdm"
source <- omopgenerics::newCdmSource(src = source, sourceType = "duckdb")

DBI::dbListTables(con) |> stringr::str_subset("prefix")
#> [1] "prefixgxwce_test_table" "prefixzrmvu_test_table"

DBI::dbDisconnect(con, shutdown=T)
```

<sup>Created on 2024-02-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by catalamarti** [comment]
In principle it inserts a table with a name:
https://github.com/darwin-eu-dev/omopgenerics/blob/742d73bcac9c6eb0cf21c7edc06d4f0993263bb0/R/classCdmSource.R#L51
And drop the same table latter:
https://github.com/darwin-eu-dev/omopgenerics/blob/742d73bcac9c6eb0cf21c7edc06d4f0993263bb0/R/classCdmSource.R#L70

So probably it is a problem with the CDMConnector method
