### ISSUE TITLE
Expand helper functions for a summarised result

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#184]
In addition to subsetResult(), it would be nice to include additional functions to help users work with a summarised result

I think in most cases these would involve extracting out a particular type of result. So this is why I would be in favour of a 
`cohortCount.summarised result`
and then even if all this did was extract out the cohortCount from the summarised result (keeping it as a summarised result) this I think would be useful for posprocessing etc

@catalamarti I think you don't like that though, but having some helper functions would be nice :)

**Comment by catalamarti** [comment]
`asCohortCount()` or `tidyCohortCount()` because it will be different than the `cohortCount` result

**Comment by edward-burn** [comment]
Maybe even just extractCohortCount? 

I guess the main question is whether all it does is filter and still return a summarised result, or whether it pivots etc too?

**Comment by edward-burn** [comment]
bind.cohort and bind.summarisedResult would have different output, right? Like I think the output for a method can differ depending on the class (just like summary() will differ in R depending on the input)
