### ISSUE TITLE
print., glimpse. or summary.SummarisedResult

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#186]
@catalamarti what about about print and summary methods for a summarised result?

Like this could be a nice way to know what type of results are contained, do I have stratification, etc

**Comment by catalamarti** [comment]
I had this in the past, but it was too simple and I deleted it, happy if someone wants to work on that

**Comment by edward-burn** [comment]
add a summary method
- number of result types
- distinct cdm names
- ......
