### ISSUE TITLE
whether to stop exporting newCdmTable

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#196]
@catalamarti I'm wondering if it is necessary to export newCdmTable? Is there a reason it could be useful? Otherwise could keep it as an internal function

**Comment by catalamarti** [comment]
afraid it is used in CDMConnector:
https://github.com/search?q=repo%3Adarwin-eu-dev%2FCDMConnector%20newCdmTable&type=code
