### ISSUE TITLE
    .softValidation = TRUE which validations are switched off?

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/omopgenerics#204]
I have a prevaltn user table where the cohorts overlap in dates, will the softvalidation = TRUE switch off this check?

**Comment by edward-burn** [comment]
Have added this in https://github.com/darwin-eu-dev/omopgenerics/pull/205

`1) a check that cohort end date is not before cohort start date,  2) a check that there  are no missing values in required columns, 3) a check that cohort duration is all within observation period, and 4) that there are no overlapping cohort entries`

**Comment by tiozab** [comment]
thanks, this means this will be available for the next release?

**Comment by edward-burn** [comment]
This is already available in the current release, but the next release will contain additional documentation on it

**Comment by tiozab** [comment]
Yes, thanks, the code for the prevalent patients worked :-)

**Comment by tiozab** [comment]
@edward-burn  just to mention: now that i amended the cohort start and end date of the drug cohort in my prevalent user cohort (because I am interested in correct duration of drug use) the dates dont overlap any more and dont cause any problems any more, that said, probably fixing the dates a step before takes care of this problem :-) while this issue was about documentation I know, I just thought I mention it somewhere :-)
