### ISSUE TITLE
create emptyCodelist

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/omopgenerics#255]

**Comment by edward-burn** [comment]
I think the omission was original with the idea that this should not be allowed, but we could of course revisit

**Comment by catalamarti** [comment]
so when the cohort does not have any codelist you get and empty codelist with `cohortCodelist` so it is weird that we can not have an empty one @edward-burn

**Comment by edward-burn** [comment]
Hmmm I think that's more a feature of CDMConnector only supporting cohortCodelist, but then I suppose someone could make their own cohort that doesn't have a codelist so maybe we should indeed have an empty version of one. I suppose this is essentially just an empty list? Or does it need to be named? Relatedly we might want to review behaviour of the validation of edge cases more generally
