### ISSUE TITLE
what does temporary mean in the context of a cdm_reference?

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/omopgenerics#302]
From my understanding omopgenerics defines the generic classes and methods for working with cdm objects and CDMConnector is supposed to be the database implementation. So omopgenerics shouldn't really need to refer to concepts/ideas that apply only to databases.

What does `temporary` mean in the context of a generic cdm? This is an idea that only applies to databases, right?

<img width="881" alt="image" src="https://github.com/darwin-eu-dev/omopgenerics/assets/10227522/ee0a9359-06ed-42ec-a21a-0c75ab23c747">

Maybe the generic should include ... and then the db_cdm implementation includes the temporary argument.

**Comment by catalamarti** [comment]
It is to be consistent with the compute implementation

**Comment by ablack3** [comment]
I don't understand what that means.
