### ISSUE TITLE
deprecate "empty___" functions in favor of "new____" with no arguments

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/omopgenerics#318]
There are several function that create empty objects. I'm wondering if we could just call "new___" with no arguments to get an empty object. 

So for example,
instead of calling `emptyAchillesTable` we call `newAchlliesTable()`. Would this work?

Here are the other "empty" functions:

emptyCdmReference
emptyCodelist
emptyCohortTable
emptyOmopTable
emptySummarisedResult

**Comment by edward-burn** [comment]
For me this is actually quite nice as it makes code like this very clear https://github.com/darwin-eu-dev/CohortCharacteristics/blob/6a27ae60f594221451c7c567b76f620a7ff73a26/R/summariseCohortTiming.R#L123

**Comment by catalamarti** [comment]
reopen if you disagree
