### ISSUE TITLE
readSummariseResult

### ISSUE THREAD

**Issue by nmercadeb** [darwin-eu-dev/omopgenerics#322]
@daniellenewby has worked with the `exportSummarisedResult` function for a network study, and when doing the shiny we thought that it would be nice to have a read function that converts it back to a summarised result. What do you think @catalamarti ?

**Comment by catalamarti** [comment]
in principle read_csv() |> newSummarisedResult() should make it to work

**Comment by nmercadeb** [comment]
It works now!
