### ISSUE TITLE
unable to bind multiple summarised_characteristics using bind function

### ISSUE THREAD

**Issue by daniellenewby** [darwin-eu-dev/omopgenerics#323]
Hey @catalamarti 

I have exported some summarised results (in this case summarised characteristics) for different data partners:

```
omopgenerics::exportSummarisedResult(summaryDemographics,
                                       minCellCount = 5,
                                       path = here("Results",db_name),
                                       fileName = paste0(cdmName(cdm),
                                                         "_summary_demographics.csv")
  )
```

So now i have a shiny where i want to read in each csv for each data partner for the demographics and bind them.

```
tableone_demo_files <- results[stringr::str_detect(results, ".csv")]
tableone_demo_files <- results[stringr::str_detect(results, "demographics")]

if(length(tableone_demo_files > 0)){

tableone_demo <- list()
settings_demo <- list()

for(i in seq_along(tableone_demo_files)){
  tableone_demo[[i]] <- readr::read_csv(tableone_demo_files[[i]],
                                                 show_col_types = FALSE) 

  settings_demo[[i]] <- tableone_demo[[i]] %>% 
    dplyr::filter(variable_name == "settings")
  
  tableone_demo[[i]] <- tableone_demo[[i]] %>% 
    dplyr::filter(variable_name != "settings")

  tableone_demo[[i]] <- tableone_demo[[i]] %>% 
    omopgenerics::newSummarisedResult(
      settings = tibble(
      result_id = 1L, 
      result_type = settings_demo[[i]]$estimate_value[3], 
      package_name = settings_demo[[i]]$estimate_value[1],
      package_version = settings_demo[[i]]$estimate_value[2],
      value = 5)
    )
  
}
```

Each element in my list which is for each data partner now has a summarised_characteristics:
`class(tableone_demo[[1]])`
[1] "summarised_result" "omop_result"       "tbl_df"            "tbl"               "data.frame" 

However, when i try to bind these:
```
demo_characteristics <- omopgenerics::bind(tableone_demo) %>% 
  mutate(cdm_name = str_replace_all(cdm_name, "_", " "))
```

I get the following error:
![image](https://github.com/darwin-eu-dev/omopgenerics/assets/16097637/1e4fc94c-ea3e-40b7-a57b-113a6c3c2b66)

However, when @nmercadeb dug into the code the result id can be updated
![image](https://github.com/darwin-eu-dev/omopgenerics/assets/16097637/118fc2fb-68a9-4f83-a05b-e3da605b364b)

We were wondering if it was something to do with the argument https://github.com/darwin-eu-dev/omopgenerics/blob/f1d741b7f48c943418bb51620f8cc6139340a4ed/R/classSummarisedResult.R#L304
and if groupping should also contain cdm_name? https://github.com/darwin-eu-dev/omopgenerics/blob/f1d741b7f48c943418bb51620f8cc6139340a4ed/R/classSummarisedResult.R#L305C1-L305C77

You can see renv_lock for the study here https://github.com/oxford-pharmacoepi/OPTIMA_incidence_survival/blob/main/renv.lock

**Comment by catalamarti** [comment]
does this code work? @daniellenewby 
```
tableone_demo_files <- results[stringr::str_detect(results, ".csv")]
tableone_demo_files <- results[stringr::str_detect(results, "demographics")]

if(length(tableone_demo_files > 0)){

x <- list()

for(i in seq_along(tableone_demo_files)){
  x[[i]] <- readr::read_csv(tableone_demo_files[[i]], show_col_types = FALSE) |> 
    omopgenerics::newSummarisedResult()  
}

sr <- Reduce(omopgenerics::bind, x)
```

**Comment by daniellenewby** [comment]
nope :)

**Comment by catalamarti** [comment]
Can you share the error?

**Comment by daniellenewby** [comment]
![image](https://github.com/darwin-eu-dev/omopgenerics/assets/16097637/1ba18c75-fac2-4441-b79b-f747c1cdfb91)

**Comment by catalamarti** [comment]
Is that when you do newSummarisedResult or when you do bind?

**Comment by daniellenewby** [comment]
bind :)
