### ISSUE TITLE
bind and result id

### ISSUE THREAD

**Issue by nmercadeb** [darwin-eu-dev/omopgenerics#336]
when binding results with = settings the result id should be the same for all of them. for instance, in the following example, all should be 1
![image](https://github.com/darwin-eu-dev/omopgenerics/assets/61558739/75b80a26-b6aa-4f2c-a0fc-88ea51279352)

**Comment by catalamarti** [comment]
Do we want to allow that the same result_id have different cdm_names? @edward-burn @nmercadeb

**Comment by nmercadeb** [comment]
I would say yes, but because as I see it result_id should identify different combinations of settings
