### ISSUE TITLE
is NA considered if we ask for unique values

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/omopgenerics#337]
so would c(1, NA, 5, NA) be considered unique (as all the numbers are different) or not (NA is repeated)

**Comment by edward-burn** [comment]
I don't think it would typically be considered as unique

``` r
waldo::compare(
  c(1, NA, 5, NA), 
  unique(c(1, NA, 5, NA)))
#> `old`: 1 NA 5 NA
#> `new`: 1 NA 5
```

<sup>Created on 2024-05-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
