### ISSUE TITLE
Move assertTables or something similar to omopgenerics

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/omopgenerics#364]
CDMConnector has a function to check that tables are in the cdm and are not empty.

@edward-burn asked about moving this to omopgenerics which seems reasonable to me.

https://github.com/darwin-eu-dev/CDMConnector/issues/449

https://github.com/darwin-eu-dev/CDMConnector/blob/72cea62dd9e151c5bc2cb2a725aa4a3321cfd6b4/R/validate.R#L148

**Comment by catalamarti** [comment]
now is in validateCdmArgument
