### ISSUE TITLE
agree on summarisedResult class

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/OMOPGenerics#4]

**Comment by edward-burn** [comment]
summarisedResult

- low-level constructor (internal)
- high-level constructor (export)
- validator (export)

Compulsary columns:
- "cdm_name": "cprd gold 202301" # cant be NA
- "result_type": "Summarised characteristics" # Sentence case, could be NA
- "package": "DrugUtilisation" # could be NA
- "package_version": "0.4.0" # could be NA
- "group_name": "cohort_name and sex" # snake_case separated by and; can not be NA
- "group_level": "cohort1 and Male" # can not be NA
- "strata_name": same than group_name
- "strata_level": same than group_level
- "variable": "age_group" # can not be NA
- "variable_level": "10 to 50" # can be NA
- "variable_type": "count" # can not be NA
- "estimate_type": ""
- "estimate"

**Comment by MimiYuchenGuo** [comment]
newSummarisedresult <- function(x) {
class(x) <- "summarised_result"
return(x)
}

**Comment by catalamarti** [comment]
#19
