### ISSUE TITLE
Change cohortAttrition, incidenceAttrition and prevalenceAttrition to attrition?

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/OMOPGenerics#41]
Just one function with a method
@edward-burn

**Comment by catalamarti** [comment]
The problem would be cohortCount as dplyr already has the count method, worth considering I think

**Comment by edward-burn** [comment]
Yep, would be nice to have the attrition method (but true about cohort count...)

**Comment by catalamarti** [comment]
lets call it settings
