### ISSUE TITLE
use stringr_replace_all instead of gsub to handle latin1-encoded characters

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/omopgenerics#441]
here is a reprex of an error we had on a study. The issue is that there are concept names in the database encoded with latin1 and not utf8 which causes a problem. 

Perhaps we could handle this in the database driver or ask the data partner to convert to utf8 but at least for now str_replace_all works ok.

``` r
b = "M\xe9ni\xe8re's disease"
gsub("_", " ", b)
#> Warning in gsub("_", " ", b): unable to translate 'M<e9>ni<e8>re's disease' to
#> a wide string
#> Error in gsub("_", " ", b): input string 1 is invalid
```

<sup>Created on 2024-08-05 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by catalamarti** [comment]
#442
