### ISSUE TITLE
Export generated cohort set - two csvs instead of one? or a single attribute?

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/OMOPGenerics#45]
@catalamarti what about exporting the cohort set and cohort attrition as tow csvs (to match two attributes)? Or alternatively have one attritbute that already contains the set and the attrition? It just seems a little inconsistent to have two attributes and one csv (but maybe I'm just being pedantic!)

**Comment by catalamarti** [comment]
everything in a single csv, two formats: `summarised_result` and `compared_result`
