### ISSUE TITLE
Specify extra, optional, columns for the summarised results

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/OMOPGenerics#46]
@catalamarti I'm thinking it might be useful to define extra columns for the summarised result here in OMOPGenerics. For example we could add:
- additional_grouping_name_1
- additional_grouping_value_1
- additional_grouping_name_2
- additional_grouping_value_2
- additional_grouping_name_3
- additional_grouping_value_3

For CohortSurvival I could then include 
- additional_grouping_name_1: c("time", "time", "time")
- additional_grouping_value_1:  c(0, 1, 2)

I'm just thinking this is a way to extend the current model in a way that still keeps some consistency across cohort survival, codelist generator, etc which contain extra columns

**Comment by catalamarti** [comment]
can we summarise this in: `additional_groupping_name`, `additional_groupping_level` ? 
and then group the same way that we group: `group` and `strata` variables?
@edward-burn

**Comment by catalamarti** [comment]
#69
