### ISSUE TITLE
omopgenerics::resultColumns(table = "settings")

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#479]
To define required settings columns. Requiring the table has package name and version, but allowing them to be NA, might for example be helpful

**Comment by catalamarti** [comment]
required columns:
- result_id
- result_type
- package_name
- package_version

for the moment I would add them as NA_character_ if they are not present

**Comment by ilovemane** [comment]
is this same as #492

**Comment by catalamarti** [comment]
- resultColumns("settings") [line 168 classSummarisedResult.R]
- add the compulsory columns to the fieldsResults dataset
