### ISSUE TITLE
Export fieldsTables as dataset

### ISSUE THREAD

**Issue by ilovemane** [darwin-eu-dev/omopgenerics#490]
Hi all, it is ok to add an argument to this function (e.g. includeFormat = T/F) if TRUE it return a tibble with column names and its column format? I will need to write it in omock, but I think it goes well here. You can assign me to this and I can add it in if you think is good idea  @catalamarti @edward-burn

**Comment by catalamarti** [comment]
export the table `fieldsTables`
- export dataset
- document dataset
- include the dataset in a vignette
