### ISSUE TITLE
consider moving startDateColumn to omopgenerics

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#491]
@catalamarti seems more like a function for omopgenerics?
https://darwin-eu-dev.github.io/PatientProfiles/reference/startDateColumn.html

**Comment by catalamarti** [comment]
create a set of functions vocabulary based

**Comment by ilovemane** [comment]
@catalamarti  shall I re export of those functions ed mention above or just copy over?

**Comment by catalamarti** [comment]
- To check where this function is used
- We would go for new argument in `omopColumns` if onlyRequired can be deprecated

**Comment by ilovemane** [comment]
This function is not used in anywhere.

**Comment by catalamarti** [comment]
- omopColumn

vs

- startDateColumn
- endDateColumn
- standardConceptColumn
- sourceConceptColumn

**Comment by catalamarti** [comment]
```
# OPTION 1
startDateColumn <- function(table) {
  omopColumn(table = table, field = "start_date")
}

omopColumn <- function(table, field, call = parent.frame()) {
  # initial checks
  assertChoice(table, optionsTable, call = call)
  
  # internal dataset
  fields$name[fields$table == table & fields$type == field]
}

# OPTION 2
omopColumn <- function(table, field) {
  # initial checks
  assertChoice(table, optionsTable)
  assertChoice(field, c("start_date", "end_date", ...))
  
  # internal dataset
  fields$name[fields$table == table & fields$type == field]
}
```
