### ISSUE TITLE
Cast cohort id as character before using paste

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/OMOPGenerics#50]
SQL server doen't like pasting an integer with a character, so better to cast the id as.character() beforehand

https://github.com/darwin-eu-dev/OMOPGenerics/blob/a314e869bec60590a7216d4e366ad6f094787a5c/R/classGeneratedCohortSet.R#L329C49-L329C49

**Comment by catalamarti** [comment]
done
