### ISSUE TITLE
naming of excluded_records excluded_subjects

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/omopgenerics#534]
https://github.com/darwin-eu-dev/omopgenerics/blob/555df1631fd22090627de87a0244427734b64d23/R/methodAttrition.R#L80-L81

suggest to name the excluded_records rather "merged_records" or collapsed_records because the records were not excluded just merged / collapsed into an era / spell.
Exclusion sounds bad and makes everybody jump.

**Comment by catalamarti** [comment]
collapsed_records make sense only if we are collapsing but the column name must be general. Reason is the place to add more explanations will, more documentation has been added
