### ISSUE TITLE
summaisedResults 

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/OMOPGenerics#57]
To consider some changes in summarisedResults class:

@edward-burn 

"cdm_name", 
**"result_name"**, 
**"package_name"**, 
"package_version", 
"group_name", 
"group_level", 
**"strata_name" (OPTIONAL),**
**"strata_level" (OPTIONAL),** 
**"variable_name" : sex,**
"variable_level" : male, 
**"variable_type" : categorical,** 
**"estimate_name" : count,**
**"estimate_type" : numeric,** 
**"estimate_value" : 5,**
**"groupping_name" (OPTIONAL),**
**"groupping_level" (OPTIONAL)**

**no extra columns are allowed**

**Comment by edward-burn** [comment]
- should we add a column with the time/ date the result was created?
- why not make strata name, strata_level, grouping_name, and grouping_level as required (as "Overall" can always be used)?
- can estimate name and estimate type be merged? 
- how do we deal with suppression? Set estimate value to missing? (I kind of like an extra column to indicate if it has been suppressed in case we have estimates that are NA for other reasons)
- why no extra columns? I would keep the flexibility of allowing them (but just not validate etc)

**Comment by edward-burn** [comment]
Add cdm_name and study_id at export
