### ISSUE TITLE
C stack usage warning

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/OMOPGenerics#59]
@catalamarti I´m getting this error if I run this test locally https://github.com/darwin-eu-dev/OMOPGenerics/blob/d5d521e96799c6cb52a9de895bcc97625fde808d/tests/testthat/test-classGeneratedCohortSet.R#L15, do you see anything similar?

![image](https://github.com/darwin-eu-dev/OMOPGenerics/assets/9583964/7ff5fe8e-d6ea-499f-b5f3-0906c3e30306)

**Comment by catalamarti** [comment]
I've been looking at this and it is due to the method $ and [[ for cdm_reference, we can speak about it

**Comment by edward-burn** [comment]
This is the problematic line of code https://github.com/darwin-eu-dev/OMOPGenerics/blob/4fb4c0d621c1683ecdf0e4b1e418da09cf59f1f7/R/classCdmReference.R#L210

**Comment by catalamarti** [comment]
In principle cdmTable just adds the class cdm_table right?

**Comment by edward-burn** [comment]
@catalamarti Could it be somewhere here? cdm reference goes to validate source which goese back to cdm reference
![image](https://github.com/darwin-eu-dev/OMOPGenerics/assets/9583964/b3f5d0d9-3540-45c2-ba41-ff213aa88005)

**Comment by catalamarti** [comment]
https://github.com/tidyverse/tibble/issues/1566

best option for the moment is unclass elements when assigning to cdm reference

**Comment by catalamarti** [comment]
#84
